### ISSUE TITLE
Update to new Issue Template

### ISSUE THREAD

**Issue by cseas** [MozillaIndia/mozillaindia.github.io#181]
## Bug/Feature/Enhancement
Enhancement

**Screenshots of the issue**
![Selection_052](https://user-images.githubusercontent.com/29686866/66412508-4be3a880-ea13-11e9-804f-1e16ab4e098f.png)

Link: https://github.com/MozillaIndia/mozillaindia.github.io/blob/gatsby/.github/ISSUE_TEMPLATE.md

We're using an old issue template. Should it be upgraded?

**Would you like to work on the issue?**
I don't really know how to.

**Comment by asdofindia** [comment]
That's really interesting - the new workflow. Instead of manually editing text (for example the bug/feature/enhancement text in the comment here itself) it will allow different templates for different kind of issues. The learn more link has enough information to get started. Can take inspiration for the content from the existing template which was added by @obitodarky

**Comment by lucasrabiec** [comment]
I take care of this issue :)

**Comment by lucasrabiec** [comment]
Hmmm, I think this solution is what you need guys: https://help.github.com/en/articles/creating-issue-templates-for-your-repository
Am I right?
